# first we have to tell what would be the base image.

FROM ubuntu 
# name of author
MAINTAINER Sheeshpal 
# update command
RUN apt-get update 

# start up executable command
CMD ["echo", "this is my first image"]


